Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: © 2013 Barch contributors
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://127.0.0.1:3001"
  host: "127.0.0.1"
  port: 3001
  <<: *defaults
